outdir: '/scratch/t.cri.yliang/ABC-GWAS/ABC-SLDSC-annot'

abc_file: '/scratch/t.cri.yliang/ABC-GWAS/ABC-by-biosample/AllPredictions.AvgHiC.ABC0.02.ModelRegions.{biosample}.cleanup.tsv.gz'

ldsc_files_yaml: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/gwas-abc/ldsc_files.yaml'
  
