abc_file: '/scratch/t.cri.yliang/ABC-GWAS/ABC-by-biosample/AllPredictions.AvgHiC.ABC0.02.ModelRegions.{biosample}.cleanup.tsv.gz'

ldsc_setup:
  python: '/gpfs/data/im-lab/nas40t2/yanyul/softwares/miniconda2/envs/ldsc/bin/python'
  make_annot: '/gpfs/data/im-lab/nas40t2/yanyul/softwares/ldsc/make_annot.py'
  ldsc: '/gpfs/data/im-lab/nas40t2/yanyul/softwares/ldsc/ldsc.py'
ldsc_files: '../../ldsc_files.yaml'