column_yaml: 'test.yaml'
gwas_file: '/gpfs/data/im-lab/nas40t2/Data/SummaryResults/imputed_gwas_hg38_1.1/imputed_{gwas_tag}.txt.gz'

ldsc_setup:
  python: '/gpfs/data/im-lab/nas40t2/yanyul/softwares/miniconda2/envs/ldsc/bin/python'
  munge_sumstats: '/gpfs/data/im-lab/nas40t2/yanyul/softwares/ldsc/munge_sumstats.py'
ldsc_files_yaml: '../../ldsc_files.yaml'