outdir: '/scratch/t.cri.yliang/ABC-GWAS/GWAS-formatted-for-SLDSC'

column_yaml: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/gwas-abc/qsub/preprocessing/02_format_gwas/column.yaml'
gwas_file: '/gpfs/data/im-lab/nas40t2/Data/SummaryResults/imputed_gwas_hg38_1.1/imputed_{gwas_tag}.txt.gz'

ldsc_files_yaml: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/gwas-abc/ldsc_files.yaml'
