#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=8gb
#PBS -e logs/run_$GWAS.err
#PBS -o logs/run_$GWAS.out
#PBS -N format_gwas

# ARGS BIOSAMPLE

source ~/.bash_profile
source ~/.bashrc

SNMK=/gpfs/data/im-lab/nas40t2/yanyul/softwares/miniconda2/envs/mixqtl/bin/snakemake

conda activate abc

cd $PBS_O_WORKDIR
cd ../../../preprocessing/format_gwas

$SNMK -s run.snmk --configfile $PBS_O_WORKDIR/config.yaml -p \
  --config gwas_tag=$GWAS \
  > $PBS_O_WORKDIR/logs/run_$GWAS.log 2>&1

