outdir: '/scratch/t.cri.yliang/ABC-GWAS/enrichment-odds-ratio'
bedfile_pattern: '/scratch/t.cri.yliang/ABC-GWAS/ABC-by-biosample/AllPredictions.AvgHiC.ABC0.02.ModelRegions.{bed_tag}.cleanup.tsv.gz'
gwas: 
  sumstats_pattern: '/gpfs/data/im-lab/nas40t2/Data/SummaryResults/imputed_gwas_hg38_1.1/imputed_{gwas_tag}.txt.gz'
  ld_clump: '/scratch/t.cri.yliang/ABC-GWAS/GWAS-ld-clump-all-snps/gwas_clump_x_{gwas_tag}.clumped_snp'
  cols:
    pval: 'pvalue'
    snpid: 'variant_id'
    chromosome: chromosome
    position: position
bed_list: '/gpfs/data/im-lab/nas40t2/yanyul/ABC_enhancer2gene/AllPredictions.AvgHiC.ABC0.02.ModelRegions.txt.gz.all_celltype_list'

bedtools_pylib: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/misc-tools/bedtools_pylib'
liftover_gwas:
  pylib: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/misc-tools/liftover_snp'
  chain: '/gpfs/data/im-lab/nas40t2/yanyul/data/hg38ToHg19.over.chain.gz'
