#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=4
#PBS -l mem=16gb
#PBS -e logs/run_$BATCH.err
#PBS -o logs/run_$BATCH.out
#PBS -N odds_ratio

# ARGS BATCH (batch of traits)

source ~/.bash_profile
source ~/.bashrc

SNMK=/gpfs/data/im-lab/nas40t2/yanyul/softwares/miniconda2/envs/mixqtl/bin/snakemake

module load gcc/6.2.0 
module load bedtools/2.29.0

conda activate abc

cd ${PBS_O_WORKDIR}
cd ../../../enrichment/odds_ratio

$SNMK -s run.snmk --configfile $PBS_O_WORKDIR/config.yaml -p --cores 4 \
  --config trait_list=$PBS_O_WORKDIR/gwas_list/$BATCH \
  > $PBS_O_WORKDIR/logs/run_$BATCH.log 2>&1

